name: projectflutter2
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  encrypt_shared_preferences: ^0.9.10
  image_picker: ^1.2.0
  image: ^4.5.4
  intl: ^0.20.2
  get: ^4.7.3
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
encrypt_shared_preferences: ^0.9.10
flutter:
  uses-material-design: true

  assets:
    - image/
